import fs from "node:fs/promises";

import { coverTemplatePath, styleTemplatePath } from "../utils/paths.js";

const DEFAULT_COVER = {
  schoolName: "Taiyuan Normal University",
  reportTitle: "课程实验报告",
  subtitle: "Program Report Generator",
  footerNote: "Generated by Report Generator"
};

const DEFAULT_STYLES = {
  page: {
    marginTop: 1200,
    marginBottom: 1200,
    marginLeft: 1440,
    marginRight: 1440
  },
  title: {
    font: "Microsoft YaHei",
    size: 36,
    color: "213547"
  },
  body: {
    font: "Microsoft YaHei",
    size: 24,
    line: 360
  },
  code: {
    font: "Consolas",
    size: 18,
    line: 280,
    background: "F6F7FB"
  },
  image: {
    maxWidth: 520,
    maxHeight: 320
  }
};

function mergeDeep(base, incoming) {
  if (!incoming || typeof incoming !== "object") {
    return base;
  }

  const result = { ...base };
  for (const [key, value] of Object.entries(incoming)) {
    if (value && typeof value === "object" && !Array.isArray(value)) {
      result[key] = mergeDeep(base[key] ?? {}, value);
    } else {
      result[key] = value;
    }
  }
  return result;
}

async function loadJson(filePath, fallback) {
  try {
    const content = await fs.readFile(filePath, "utf8");
    return mergeDeep(fallback, JSON.parse(content));
  } catch {
    return fallback;
  }
}

export async function loadTemplates() {
  const [cover, styles] = await Promise.all([
    loadJson(coverTemplatePath, DEFAULT_COVER),
    loadJson(styleTemplatePath, DEFAULT_STYLES)
  ]);

  return { cover, styles };
}
